### ISSUE TITLE
What data is available?

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#101]
@craig-willis - I like the idea of this graph
https://terraref.gitbooks.io/terraref-documentation/content/user/what-data-is-available.html# 

Can it be live? The Y axis should be renamed

stereoTop = RGB
SWIR = SWIR
VNIR = VNIR
flirIr = IR
priSensor = PRI
ndviSensor = NDVI
cropCircle = Active Reflectance
ps2Sensor = PSII

**Comment by dlebauer** [comment]
@jdmaloney is there a place where the transfer logs can be queried? 

Or @max-zilla is there a way to query datasets from Clowder?

**Comment by rachelshekar** [comment]
Here's an example from Neon http://data.neonscience.org/view-data-availability

**Comment by rachelshekar** [comment]
@jdmaloney  - is there a place where the transfer logs can be queried?
@max-zilla  - is there a way to query datasets from Clowder?

**Comment by craig-willis** [comment]
I will work with JD on this next week, after things settle down with the various system outages.

**Comment by rachelshekar** [comment]
also compile into quick view

**Comment by rachelshekar** [comment]
http://terra-logging.ncsa.illinois.edu:3000/dashboard/db/sensor-file-counts-and-size?from=now-6M&to=now

**Comment by rachelshekar** [comment]
https://terraref.gitbooks.io/terraref-documentation/content/user/what-data-is-available.html

JD - please link your new page

**Comment by dlebauer** [comment]
@jdmaloney please also link to the place where I can query these data and regenerate the image in the documentation
