### ISSUE TITLE
missing metadata link

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#102]
on https://terraref.gitbooks.io/terraref-documentation/content/tutorials/accessing_sensor_information.html
did you intend to link "For further information of the Sensor Metadata see" here: https://github.com/terraref/documentation/blob/master/tutorials/accessing_sensor_information.md

**Comment by craig-willis** [comment]
@dlebauer 
I'm happy to make this change, but just want to confirm the process for modifying these tutorial pages.  You modify the .Rmd files in Rstudio then generate the .md file?

**Comment by dlebauer** [comment]
@craig-willis yes - for pages with .Rmd files, these should be updated. After you submit the pull request on the .Rmd file I can recompile the md files Rstudio

**Comment by craig-willis** [comment]
PR ready for review https://github.com/terraref/documentation/pull/107
