### ISSUE TITLE
Requirements/mockup for revised landing page

### ISSUE THREAD

**Issue by craig-willis** [terraref/documentation#106]
Discuss and collect requirements for the revised landing page UI (http://terraref.org/) for the upcoming Phenome meeting.  The ultimate goal is to refactor the landing page UI to improve usability for end users.

Completion criteria:
- [x] Requirements captured in [Google doc](https://docs.google.com/document/d/18Re-yOplJmzcvobMlZO45AnFYndagOS4QnECAtWVIZs/edit)
- [x] Preliminary mockup 
- [x] Review meeting with relevant stakeholders

**Comment by craig-willis** [comment]
@dlebauer @rachelshekar 
Do you have any sense of where you'd like to start on this or example sites? I've been looking at http://www.neonscience.org/, https://www.dataone.org/, and https://nsidc.org/data/modis/.

**Comment by dlebauer** [comment]
@craig-willis these are all good places to start.

Just to reiterate, the most important thing to focus on at this point is making sure that we have a useful navigation path ... so for the terraref.org, we can mostly change which links are found at the top of the page, e.g. having documentation and data links. Then we can focus on making the data discovery page accessible, i.e. a page like with neon it goes neonscience.org --> neonscience.org/data-resources/get-data.

Do you think it would be worth engaging someone with experience in UI design at this point?

**Comment by dlebauer** [comment]
The UI for the NEON data products page looks pretty straightforward: http://data.neonscience.org/data-product-catalog

**Comment by craig-willis** [comment]
@dlebauer  
Sorry for the late response on this.  I can't argue with bringing in a UI person, if you have one in mind.  I guess I'm unclear on the specific goals of this issue.  My understanding is that we are prioritizing the short-term re-organization of terraref.org (more of an information organization problem than UI design problem).

**Comment by craig-willis** [comment]
Have added Phase I redesign notes from discussion with @dlebauer to Google Doc linked in description.  Starting work on preliminary mockup fork.

**Comment by dlebauer** [comment]
> Starting work on preliminary mockup fork.

@craig-willis ... I thought a 'mockup' could be a sketch rather than code? Please check in with @rachelshekar

**Comment by craig-willis** [comment]
@dlebauer It just seemed easier to try to rough out in code, since Jekyll has limitations (i.e., submenus, etc).  I've added a rough mockup of the menu and data page to the Google Doc. I'll discuss with @rachelshekar today.

**Comment by rachelshekar** [comment]
@craig-willis I made comments

**Comment by craig-willis** [comment]
@dlebauer @rachelshekar 

I experimented with changing the theme, per discussion with Rachel.  I've pushed to my personal git pages site:

https://craig-willis.github.io/

This is the minimal-mistakes theme with the existing terra-ref content.  There are a few differences with the so simple theme (no floating logo, I had to embed it in the photo; some of the _config.yml options are different, but I think we can support most things in the end).

Anyway, let met know if you have any comments.

**Comment by dlebauer** [comment]
Sorry I missed the discussion, but I thought we had decided to treat the website redesign separately from the content. Our immediate need is to make it easier for users to find the data and technical information that they need. This can be done by adding a /data and a /science page with appropriate links.

The simplified navigation on the new theme looks good, but this can be done with the current theme. It doesn't provide nested navigation that we discussed. When we do a 'redesign' to make the site more professional, we can choose a new theme. I gather Rachel would prefer Wordpress, and I am in favor of this if it makes it easier for people to contribute content. Perhaps the site redesign should be a separate issue. Our first priority should be content ...

**Comment by craig-willis** [comment]
@dlebauer 
Sorry for the misunderstanding. The discussion with @rachelshekar last week was about both content and theme changes, which I assumed you had agreed to.  There seems to be a fair amount of misunderstanding/miscommunication around this issue. 

I'll focus on content changes only until I hear otherwise.

**Comment by craig-willis** [comment]
@rachelshekar 
I'll be doing final work on this in the coming days based. Are you expecting any other changes than what we've already discussed (Team, Press, etc)?

**Comment by craig-willis** [comment]
I've pushed the latest changes to https://craig-willis.github.io
* Added "Press" page
* Updated "Team" page with profile images

Looking back over my notes from Friday, I see the following:
* Need to add Genomics data, but there's a dependency on making the data public in Cyverse.  I'll need to know what link to use.
* Separate out weather data, available via Geostreams. However, this isn't ready yet. Not sure what to do here.
* Data needs to be more prominent.  I don't have a clear idea of how to execute on this at the  moment.

**Comment by dlebauer** [comment]
* @nfahlgren what is the timeline for having the Genomics data available through the Cyverse data store? 
* @max-zilla what is the timeline for the geostreams interface?

**Comment by dlebauer** [comment]
@craig-willis one thing I notice is that the footer is left-aligned rather than centered. I'd just assume we remove it as spend a lot of time fiddling with the code.

**Comment by nfahlgren** [comment]
@dlebauer @craig-willis once the permissions on the terraref datastore are set to public, it should show up here: http://datacommons.cyverse.org/browse/iplant/home/shared. Permissions are set to allow the coge user access, but otherwise it's private. Maybe things changed but I thought that was intentional pending publication?

**Comment by rachelshekar** [comment]
I'm putting edits here: https://drive.google.com/drive/folders/0B0lCOAt29Y79TDh4YjZEVzRVVVk?usp=sharing

**Comment by dlebauer** [comment]
@nfahlgren we can make it public as long as there is a link to the data use policy that defines the pre-publication embargo for this purpose.

**Comment by rachelshekar** [comment]
@craig-willis   RE: Data needs to be more prominent
I like how neon icons take you straight to the data but there's an link underneath each icon for "about".  This is similar to what Rob suggested.
http://data.neonscience.org/home

**Comment by rachelshekar** [comment]
images for press releases
https://drive.google.com/open?id=0B0lCOAt29Y79azl4VGJLRnI5ZlU

**Comment by dlebauer** [comment]
can we add the images for press releases here:
https://drive.google.com/drive/u/0/folders/0By_PDCcY5g2JNkFwYTZMdnF4RVE so
that they are all in the same place?

**Comment by rachelshekar** [comment]
Update project overview with this info https://docs.google.com/presentation/d/1MbDf5DXVSCYu7iIa1MLIlqm9S7C30kNRx4-xBw1PDks/edit#slide=id.p

**Comment by rachelshekar** [comment]
@dlebauer -  i can if you want but they're not ours to share.

**Comment by dlebauer** [comment]
The data release policy is here:
https://terraref.gitbooks.io/terraref-documentation/content/user/data_release_policy.html

**Comment by nfahlgren** [comment]
@dlebauer thanks! Do I just put a README that points to that page and/or repeats it. And/or post the actual FL agreement with the data?

**Comment by craig-willis** [comment]
@rachelshekar I could use a little more guidance on the project overview info linked above.  Is this replacing the current project info or inserted as separate sections (if so where). I expect you want the images included.

**Comment by craig-willis** [comment]
@rachelshekar I think I've addressed most of your feedback except for the project overview info (above).  I think we'll need more content for the individual data description pages, and I could certainly use help on the content if possible.

**Comment by dlebauer** [comment]
@nfahlgren for now, I would put the text in a README the more we can put this in front of people the better. 

Once we assign a permanent url (terraref/reference-data#24) we can put a summary with a link to the full agreement.

**Comment by nfahlgren** [comment]
@dlebauer sounds good

**Comment by rachelshekar** [comment]
Overview text for @craig-willis : https://docs.google.com/document/d/1Px4ew_nnVBP70t_CbLAPvoMzw0ZOf3U2a3SaGRrNOAg/edit?usp=sharing
 and https://drive.google.com/drive/folders/0B0lCOAt29Y79aTlMQ0xQM1A4MTQ?usp=sharing

**Comment by craig-willis** [comment]
Thank you, @rachelshekar. I've updated the about page and added the images. 

Are we nearing the end?   I'll submit a PR when I have final thumbs up from you.

**Comment by craig-willis** [comment]
@dlebauer and @rachelshekar 
I've created a pull request from my fork for your review.  

Note: the PR contains an incorrect CNAME and _config.yaml. These are necessary for the site to be viewable at my craig-willis.github.org.  After the PR is merged, we'll need to update these to the correct values.

**Comment by craig-willis** [comment]
Closing this issue, as the PR was merged.
