### ISSUE TITLE
Update links to clowder in documentation

### ISSUE THREAD

**Issue by dlebauer** [terraref/documentation#110]
Lots of clowder links have changed. These need to be updated 

https://github.com/terraref/documentation/search?q=terraref.ncsa.illinois.edu+clowder&type=Code&utf8=%E2%9C%93

**Comment by dlebauer** [comment]
This is mostly done. The current problem is that the collections are in a private space and thus require login even though the individual datasets are public.

**Comment by max-zilla** [comment]
closely related to #116. will continue discussion there.
