### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#111]
Overall, many explanatory steps really need some screenshots to complement written instructions. For example, the section ‘analyzing data in clowder’ found here could really use some visuals.

**Comment by craig-willis** [comment]
@dlebauer  Should this move into the new sprint?

**Comment by dlebauer** [comment]
there are a bunch of images from https://github.com/terraref/reference-data/issues/194 such as 

![image](https://user-images.githubusercontent.com/464871/31248641-1a7ff8be-a9da-11e7-86e2-f0e8ec673079.png)

that give an overview of the plot layout - and for the past few seasons we have been using the same. These aren't very difficult to generate in ArcGIS or R from the field (similar to the 'map' tab in https://traitvis.workbench.terraref.org/ that works for the maricopa seasons)
