### ISSUE TITLE
Clarify and organize protocols

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#112]
The term ‘protocol’ should probably be better defined on its page. I might just put a bit more language about how these processes need to be adhered to in order to replicate the results, and explain the level of effort going into calibration methods to standardize across the different grow sites. This will lend some confidence to the ability to use the different datasets with less threat of incomparable data.

Also, Link field protocols to variable definitions in BETYdb (? or is this circular? Where is the canonical reference)

**Comment by dlebauer** [comment]
canonical reference for field protocols is the methods definitions in BETYdb --- these have citations that can link back to this document, protocols.io, or other independent documentation.

Currently we have protocols scattered around this book, protocols.io, readme files (for the software), and the methods table in betydb. I While it would be great to consolidate these, they vary in complexity. Here are some methods in BETYdb: https://terraref.ncsa.illinois.edu/bety/api/v1/methods?key=9999999999999999999999999999999999999999 and some examples of experimental designs: https://terraref.ncsa.illinois.edu/bety/api/v1/experiments?key=9999999999999999999999999999999999999999
