### ISSUE TITLE
Tutorial to introduce Plant CV data and software

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#123]
### Overview 

(updated Feb 5 2017 by @dlebauer)

Write tutorial to introduce people to TERRA REF's plantCV dataset and pipeline

* PlantCV output in sample space https://terraref.ncsa.illinois.edu/clowder/datasets/589519294f0c0650d062913f?space=57e42cd44f0cff4b58dd3eea (this is in public sample space, you can add more). 

This should go in the terraref/tutorials repository.
 
### Completion Criteria

* [ ] a self-guided intro to the plantCV data and pipeline 
   * intro may point to this video https://youtu.be/dCNYEl3ld0s of all steps from setting up pipeline to uploading / processing data
   * link to documentation of setting up Clowder
* [ ] explore a plantCV dataset in the Clowder interface (@rachelshekar)
  * Users should watch this video about how to start with Clowder web interface starting from 2m31s: https://youtu.be/dCNYEl3ld0s?t=2m31s 
* [ ] @craig-willis perhaps write up instructions for using the the plantCV docker image terraref/computing-pipeline#244 from within ndslabs. Please download the sample dataset and put it in a folder path that replicates the one on Roger.
* [ ] demonstrate how to explore the sample dataset from within iPython and / or Rmd notebook (@nfahlgren)
   * cross reference extracting associated traits from BETYdb via url-API, e.g.
        * https://terraref.ncsa.illinois.edu/bety/api/beta/cultivars?name=<GENOTYPENAME>&key=9999999999999999999999999999999999999999
        * see also / cross reference https://github.com/terraref/tutorials/blob/master/traits/02-danforth-phenotyping-facility.Rmd
* [ ] (further reading, i.e. links): how the plantCV pipeline can be adopted by other groups (@yanliu-chn) 
   * video shows how to set up Clowder+PlantCV cloud system https://youtu.be/dCNYEl3ld0s
   * is there a tutorial or documentation for running the plantCV pipeline somewhere? Linking to this is sufficient

**Comment by nfahlgren** [comment]
Would this work? http://plantcv.readthedocs.io/en/latest/. We have multiple tutorials in our documentation. Or something more TERRA-REF specific?

**Comment by dlebauer** [comment]
It would be great to have something that uses terraref data for tutorials.

**Comment by dlebauer** [comment]
Issue moved to [terraref/tutorials #2](https://github.com/terraref/tutorials/issues/2) via [**ZenHub**](https://www.zenhub.com/)
