### ISSUE TITLE
Revisit sensor naming

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#125]
- [ ] Under data products, it says NDVI and PRI sensors are multispectral imagers. I don’t think this is right – they just give values, no images.
- [ ] Under data products and environmental conditions, you misspelled the name of the environmental sensor. It’s Thies Clima, not Theis Clima. Possibly spelled wrong elsewhere as well.

In the Google Doc “Maricopa 2016 Experimental Plan Summary : sensors"
- [ ] None of the side-look sensors appear to be included in this list
- [ ] I think some of this is very ambiguously named. For example, the stereo-VIS row is actually 2 RGB cameras. And don’t we have a flash on these cameras for night operation, plus all of those halogen lights? Also, the name ‘3-D scanner. it’s really a laser line scanner (we have multiple systems that perform 3-d scans)

**Comment by rachelshekar** [comment]
- [ ] Under data products, it says NDVI and PRI sensors are multispectral imagers. I don’t think this is right – they just give values, no images.
- [ ] Under data products and environmental conditions, you misspelled the name of the environmental sensor. It’s Thies Clima, not Theis Clima. Possibly spelled wrong elsewhere as well.

In the Google Doc “Maricopa 2016 Experimental Plan Summary : 
- [ ] Sensors”: None of the side-look sensors appear to be included in this list
- [ ] I think some of this is very ambiguously named. For example, the stereo-VIS row is actually 2 RGB cameras. And don’t we have a flash on these cameras for night operation, plus all of those halogen lights? Also, the name ‘3-D scanner. it’s really a laser line scanner (we have multiple systems that perform 3-d scans)

**Comment by smarshall-bmr** [comment]
I'm in agreement on the NDVI and PRI, they are both simple multispectral sensors. The name StereoVIS comes from the HMI provided name of the two RGB cameras which is a system that I can't modify names in so I've just been running with it.

As far as the side sensors in the experimental plan, I think the general consensus has been that they aren't useful for collecting data in their current orientation. We'll probably have to have a discussion on what to do with them in the future.

**Comment by dlebauer** [comment]
> As far as the side sensors in the experimental plan, I think the general consensus has been that they aren't useful for collecting data in their current orientation.

Indeed, they wouldn't be useful for the evaluation of different genotypes. At the same time, it would be useful to collect data from them to understand the potential of such sensors for reconstructing plant architecture. It is more a matter of time / priority.

However, until / unless we turn them on we can leave them out of the documentation.

We can clarify that stereoVis is stereo-RGB in the documentation. In this case and for other sensors, it would be useful to provide alternative names for the sensors in the documentation but _not_ in the HMI metadata generation system. Alternative names can be provided downstream (e.g. we can change the names in clowder datasets and metadata if this is desirable).
