### ISSUE TITLE
enhancing documentation

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#127]
- This is very dense. How can we simplify it? If we reduce the content, there will be less for people to complain about. For example, maps of the experimental design would be nice but really?
- We need to make sure that the rest of the team is contributing.

**Comment by dlebauer** [comment]
We could also split it into different books or sections. 

If we compile the documentation using the gitbook cli, we can have different SUMMARY.md files that compile different subsets.

We could have different books, e.g. for

* Science objectives and data access 
  * science objectives 
  * data formats / web interfaces
  * tutorials / examples
* Data transfer and computing pipeline 
  * including algorithms, software
  * how to add / development section

Just an idea ... what do others think?
