### ISSUE TITLE
Document git workflow 

### ISSUE THREAD

**Issue by dlebauer** [terraref/documentation#134]
Does this go in documentation or Wiki?

... or in Contributing.md?

@czender could you outline the workflow that works for you re terraref/computing-pipeline#233?

**Comment by czender** [comment]
```
# Create new branch
git checkout -b newfeature
# Make local changes
git commit -am 'foo'
# Push local changes
git push origin newfeature
# Alternative to above: feature-based workflow (https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow)
git push -u origin newfeature
# Delete local branch once it is merged upstream
git branch -d newfeature
```
Other required steps are difficult to document because they occur sporadically and I don't understand the terminology. E.g., when newfeature is branched from an old version of master, or master changes and conflicts with newfeature.
