### ISSUE TITLE
Write Glossary

### ISSUE THREAD

**Issue by dlebauer** [terraref/documentation#14]
One sentence for each of the software / data / computing pipeline stuff

Assigned to Rachel, reply with questions

**Comment by rachelshekar** [comment]
@dlebauer - regarding documentation: 
* [ ] Need documentation for Danforth pipeline, experimental design, sensors, measurements
* [ ] Under Existing data standards:
"One implementation of CF for ecosystem model driver (met, soil) and output (mass, energy dynamics)
Standardized Met driver data
Terrestrial Ecosystem Model outputhttp://mstmipsynthesis.pbworks.com/w/page/25673213/FrontPage"
  * [ ] What is "CF"?  
  * [ ] The link to the mstmip page does not work without a login.  Do you want to keep the link, add login information, ...?
* [ ] We need a page for “cyberinfrastructure” 
* [ ] We need a page for “technical team”.  Is this the same as the Computing Pipeline Development Team team?
* [ ] Data product levels are not mentioned elsewhere - what data do they refer to?
* [ ] Why is API under Data Standards?  Is this different than the API under "software"?
* [ ] "Data Storage" under software and "data backup" should be combined.

**Comment by rachelshekar** [comment]
working document: 
https://docs.google.com/document/d/1Xy8mR1SdzBxawB5ZRmwjjAcPPuZoensYL7dze-ILkPI/edit?usp=sharing

**Comment by rachelshekar** [comment]
Created pull request https://github.com/terraref/documentation/pull/26

**Comment by craig-willis** [comment]
PR was merged long ago
