### ISSUE TITLE
How to import trait database

### ISSUE THREAD

**Issue by dlebauer** [terraref/documentation#153]
Based on https://github.com/terraref/reference-data/issues/111 and https://github.com/terraref/computing-pipeline/issues/302 

Changes to load.bety.sh described here: https://github.com/PecanProject/pecan/issues/1406

How to import terraref data:

This is using the [load.bety.sh](https://github.com/PecanProject/pecan/blob/develop/scripts/load.bety.sh) script that has been updated by @robkooper and is currently on a branch here:

https://raw.githubusercontent.com/PecanProject/pecan/357b70e21592375827e9c55bc5e1ce8e3426bd78/scripts/load.bety.sh

### Initial import

```
load.bety.sh -c -u -m 99 -r 0 -w https://terraref.ncsa.illinois.edu/bety/dump/bety0/bety.tar.gz
load.bety.sh -m 99 -r 6 -w https://terraref.ncsa.illinois.edu/bety/dump/bety6/bety.tar.gz
```

### Scheduled sync 

Now you should be able to setup cron job to periodically (we often use hourly or daily) import the data using the same as above, except remoe the `-c` flag from the first line :

```sh
load.bety.sh -m 99 -r 0 -w https://terraref.ncsa.illinois.edu/bety/dump/bety0/bety.tar.gz
load.bety.sh -m 99 -r 6 -w https://terraref.ncsa.illinois.edu/bety/dump/bety6/bety.tar.gz
```

Note that this will overwrite any changes that you have made to rows with id fields between 1-1 billion and 6 billion+1 to  7 billion.

**Comment by dlebauer** [comment]
From within docker 

```sh
docker run --name betydb -p 5432:5432 terraref/betydb-postgis
```

## to enter 

```sh
docker exec -it betydb bash
```

**Comment by craig-willis** [comment]
@dlebauer Should this move into the new sprint?

**Comment by dlebauer** [comment]
Yep

**Comment by max-zilla** [comment]
there is a PR to add this to documentation.
