### ISSUE TITLE
Update Genomics documentation

### ISSUE THREAD

**Issue by dlebauer** [terraref/documentation#165]
Need to know what we have, how it was produced, how users can access it, advantages / disadvantages of different pipelines and outputs.

Current documentation:

* data: https://github.com/terraref/documentation/blob/master/products/genomics-data.md and 
* pipeline here: https://github.com/terraref/documentation/blob/master/genomic-data-product.md
* lines sequenced:
  * year 1 https://github.com/terraref/documentation/blob/master/user/sorghum-lines-genomics.md
  * year 2 https://github.com/terraref/documentation/blob/master/user/sorghum-lines-genomics-year-2.md

On Cyverse, the following path /iplant/home/shared/terraref/genomics/derived_data/bap/resequencing/Danforth_center contains two folders, gvcf and hapmap, of the BAP that was sequenced as part of the TERRA project. The first folder contains all of the individual g.vcf files and the other contains the hapmap that were produced here at the Danforth Center using the methods outlined in the TERRA ref online documentation. 
 
On CoGe, the year one gvcf SNP data has been made public ... how people can access this data TBD

Genomics data from KSU?

**Comment by zhenbinHU** [comment]
@dlebauer Hi David, we have submitted all genomic data from KSU to Globus by early time this year (2017).Right? And we don't have new genomic data generated.

**Comment by dlebauer** [comment]
The genomic data is on Roger and the cyverse data store, but I can't find
any documentation - what what is there, how it was generated, how it can be
used ...

**Comment by nfahlgren** [comment]
Not saying it’s all complete, but you can’t find any? There are multiple documentation pages on the genomics data.

Noah

**Comment by dlebauer** [comment]
@nfahlgren my comment https://github.com/terraref/documentation/issues/165#issuecomment-344587928 was specifically addressing the KSU data ...

I did find a lot of good documentation from last year, and provided links in the original post https://github.com/terraref/documentation/issues/165#issue-273894851 ... and these all should be updated before we submit the data paper in Feb.
