### ISSUE TITLE
How to add a new season 

### ISSUE THREAD

**Issue by dlebauer** [terraref/documentation#187]
1. Add one or more new experiments to the experiments table: 
 
```sql
insert into experiments (name, start_date, end_date, description, design, user_id) 
values ('MAC Season 6: Sorghum BAP', '2017-04-26', '2018-10-01', '', '', 6000000004)
```

should be able to do this via terraref.ncsa.illinois.edu/bety/experiments/new but there is a bug https://github.com/PecanProject/bety/issues/581 but 

2. create plot definitions in the sites table

two ways of doing this: either a) Copy plot definitions from prev. season or b) import from shapefile

a) copy from prev. season

```sql
with season6 as (
  select city, state, replace(sitename, 'Season 4', 'Season 6') as sitename, greenhouse, geometry, time_zone from sites where sitename like '%Season 4%' 
)
insert into sites (city, state, sitename, greenhouse, geometry, time_zone) select * from season6
```

b) import from shapefile (preferred, if available)

you can use the shp2pgsql software installed w/ PostGIS to convert shapefiles into postGIS geometries. 
- documentation: http://www.bostongis.com/pgsql2shp_shp2pgsql_quickguide.bqg
- example https://github.com/terraref/reference-data/issues/126#issuecomment-314580044
- or there may be some R tools to do this

3. Associate experiments with sites

```sql
insert into experiments_sites (experiment_id, site_id) 
   select e.experiment_id, s.site_id 
        from (select id as experiment_id from experiments where name = 'MAC Season 6: Sorghum BAP')  as e 
     cross join 
         (select id as site_id from sites where sitename like 'MAC Field Scanner Season 6%') as s
```

examples of how to select a subset of plots (sitenames) for diff't experiments: https://gist.github.com/dlebauer/f083056af7a835c594a9167373c37773#file-mac_season4_experiments-sql

4. Create new treatments for this experiment

```sql
TBD
```

5. Associate experiments with treatments

```sql
insert into experiments_treatments (experiment_id, treatment_id) 
   select e.experiment_id, t.treatment_id 
        from (select id as experiment_id from experiments where name = 'MAC Season 6: Sorghum BAP')  as e 
     cross join 
         (select id as treatment_id from treatments where name like 'MAC Season 6: Sorghum BAP') as s
```

**Comment by dlebauer** [comment]
Add citation - sites relationships example: https://github.com/terraref/reference-data/issues/192#issuecomment-343641802

```sql
INSERT INTO citations_sites (citation_id, site_id) 
   SELECT c.id, s.id 
   FROM (select id from citations where author = 'Andrade, Pedro') 
     AS c CROSS JOIN (select id from sites where sitename like 'MAC Field Scanner%'
    and id not in (select distinct site_id from citations_sites where 
          citation_id not in (select id from citations where author = 'Andrade, Pedro'))
) AS s;

```

**Comment by dlebauer** [comment]
outline: 

```
# Beginning of season metadata

## Add Experiment
## Add Treatment
## Add plots (sites)
## Add citation - sites relationships

# For a new extractor

## Add variables

use existing or create new one
follow standard naming if possible

## Add methods
```

**Comment by dlebauer** [comment]
This can be written up and tested on seasons 5 (https://github.com/terraref/reference-data/issues/211) and 7 (TBD).

**Comment by kimberlyh66** [comment]
TERRA REF specifics have been added to Metadata Entry Workflow document on OSF. A link to OSF document has been added to betydb data entry docs.

**Comment by dlebauer** [comment]
Looks great, thanks!
