### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#25]
* [ ] Need documentation for Danforth pipeline, experimental design, sensors, measurements
* [ ] Under Existing data standards:
"One implementation of CF for ecosystem model driver (met, soil) and output (mass, energy dynamics)
Standardized Met driver data
Terrestrial Ecosystem Model outputhttp://mstmipsynthesis.pbworks.com/w/page/25673213/FrontPage"
  * [ ] What is "CF"?  
  * [ ] The link to the mstmip page does not work without a login.  Do you want to keep the link, add login information, ...?
* [ ] We need a page for “cyberinfrastructure” 
* [ ] We need a page for “technical team”.  Is this the same as the Computing Pipeline Development Team team?
* [ ] Data product levels are not mentioned elsewhere - what data do they refer to?
* [ ] Why is API under Data Standards?  Is this different than the API under "software"?
* [ ] "Data Storage" under software and "data backup" should be combined.

**Comment by rachelshekar** [comment]
We're starting over with new documentation. The outline is https://docs.google.com/document/d/1BI8-gQRMyBsacINxRd_lsUOMMHurH2eaiZPqtrgh7EM/edit

Rachel will paste text into the document and assign sections to people to edit.

**Comment by dlebauer** [comment]
@rachelshekar I think google docs is great place for drafting an outline, but gitbook will be easier for development. It is easy to generate a google doc, website, pdf, ebook etc from gitbook, but it will be much harder to generate a gitbook (with figures, code syntax highlighting, etc) from a google document. Key question is at what point do we re-orgainze the gitbook?
