### ISSUE TITLE
data transfer documentation

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#40]
https://github.com/terraref/documentation/blob/version1/data-transfer.md

**Comment by jdmaloney** [comment]
@rachelshekar I'm getting a 404 Error for this page, is there a new link?

**Comment by dlebauer** [comment]
@jdmaloney yes we killed the version1 branch. Try https://github.com/terraref/documentation/blob/master/data-transfer.md

**Comment by jdmaloney** [comment]
@dlebauer Yep, that link worked.  Filled out all the information we currently have for that page.  Leaving open?  As we'll need to add KSU, etc. once we get that information

**Comment by dlebauer** [comment]
@jdmaloney probably easier to create a new and more specific issue about adding KSU to the pipeline and close this. That way we get to close issues and keep them narrow.
