### ISSUE TITLE
developing clowder extractors documentation

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#42]
https://github.com/terraref/documentation/blob/version1/developing-clowder-extractors.md

**Comment by max-zilla** [comment]
https://opensource.ncsa.illinois.edu/confluence/display/CATS/Extractor+Development I updated this a couple weeks ago - not specific to TERRA but about development in general.

FWIW, the .md file you link to above already includes a link to this wiki page, so maybe we can close this issue.
