### ISSUE TITLE
genomic data product creation 

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#46]
https://github.com/terraref/documentation/blob/version1/genomic-data-product.md

**Comment by dlebauer** [comment]
I don't see anything here https://github.com/terraref/documentation/blob/master/genomic-data-product.md

**Comment by nfahlgren** [comment]
The two files I edited were: https://github.com/terraref/documentation/blob/master/products/genomics-data.md and https://github.com/terraref/documentation/blob/master/user/sorghum-lines-genomics.md. Is genomic-data-product.md also in the book?

**Comment by dlebauer** [comment]
Thanks- there's been lots of rearranging so it probably got orphaned
