### ISSUE TITLE
data storage and computing workbench overview

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#59]
https://github.com/terraref/documentation/blob/version1/workbench-overview.md

**Comment by rachelshekar** [comment]
https://terraref.gitbooks.io/terraref-documentation/content/user/using-analysis-workbench.html

@craig-willis and @dlebauer I don't know what app to install in workbench to the data in clowder.  There's no documentation for this.

**Comment by dlebauer** [comment]
@rachelshekar start here: https://github.com/terraref/tutorials/blob/master/README.md

follow link after 'to get started' which is where the documentation currently lives
