### ISSUE TITLE
Document hyperspectral imagery pipeline

### ISSUE THREAD

**Issue by czender** [terraref/documentation#6]
Add pointers to the hyperspectral scripts and usage examples. Main hyperspectral documentation page is [here](terraref/documentation/hyperspectral_data_pipeline.md).

**Comment by czender** [comment]
Main hyperspectral documentation page is [here](https://github.com/terraref/documentation/blob/master/hyperspectral_data_pipeline.md) (I'm still inexperienced at documenting stuff in GitHub. Bear with me...

**Comment by hmb1** [comment]
hi i am hmb1 want write access to the doc repo

**Comment by dlebauer** [comment]
granted

**Comment by dlebauer** [comment]
FYI the documentation can be edited in github but the files are unordered. Easiest to use either the web based ide (which automatically syncs with the github repository)  the desktop ide, or command line tools https://github.com/GitbookIO/gitbook

**Comment by czender** [comment]
Just placed sample hyperspectral imagery data file and CDL metadata at
http://dust.ess.uci.edu/tmp/test.nc4 and test.cdl, respectively.

**Comment by dlebauer** [comment]
@czender I just checked out the test.nc4 file and noticed a few things:

* all values were either 1 or 0 but units are 'ratio of actual to fully exposed (saturated) channel'. Is this expected (and/or what input file did you use?)
* variable names are different from CF names specified in reference-data#14. Are these CF compliant?

**Comment by czender** [comment]
Thank you for noticing this. Values should not be (all) 0 or 1. There must have been a rounding issue. I will fix it. Right now working on speed. The variable name I picked for now is 'xps_frc' for "exposure fraction". It is yet not a reflectance and has no CF counterpart of which I am aware. When we have a refletance, that will be a CF quantity, and we'll annotate with its standard_name. Am creating a newer netCDF file from a more recent (March 5) raw file. The existing test is old (October) and the format has changed slightly. Will post again when new netcdf is up.

**Comment by rachelshekar** [comment]
Moved to https://github.com/terraref/documentation/blob/version1/hyperspectral-data-product.md
