### ISSUE TITLE
how to use betydb

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#64]
https://github.com/terraref/documentation/blob/version1/user/using-betydb.md

**Comment by rachelshekar** [comment]
@gsrohde - this looks great but the link to the image of the search box is broken

**Comment by gsrohde** [comment]
@rachelshekar It's broken in the GitBook viewer, but I think it works correctly at the GitBook site, https://terraref.gitbooks.io/terraref-documentation/content/user/using-betydb.html or if you download the PDF version at https://www.gitbook.com/download/pdf/book/terraref/terraref-documentation.  Let me know if not.

**Comment by rachelshekar** [comment]
I see it now.  Thanks!
