### ISSUE TITLE
Genomic Data Standards

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#74]
https://github.com/terraref/documentation/blob/version1/genomic-data-standards.md

**Comment by craig-willis** [comment]
I just pushed a change to this page, basically harvesting from the old genomics-pipeline page.  @nfahlgren, I'm happy to do as much of this documentation as possible. Please feel free to direct me to any information that you think would be helpful to include.

**Comment by nfahlgren** [comment]
@craig-willis @phloz Phil, could you provide Craig with the information about the workflow you used to process the genomic data?

**Comment by nfahlgren** [comment]
@craig-willis For the sample metadata information, it seems like it would be useful to have it in JSON-LD format, if we can use it that way anyhow. I started a table (for now) here: https://docs.google.com/spreadsheets/d/1ntnps0u0c8O4xxrv_VVqfxDkpmppCGdFIIWLMmRCeSM/edit?usp=sharing

The columns are based on the MIxS Plant Specimen standard: http://gensc.org/the-plant-specimen-contextual-data-consensus/

Let me know what you think.

**Comment by craig-willis** [comment]
Thanks @nfahlgren 

I can create the JSON-LD data based on the spreadsheet and MIxS standard.

I'm not clear where this fits in the process.  Where does the spreadsheet data come from? Will this data end up (or is it already) in Clowder?

**Comment by phloz** [comment]
@craig-willis I am writing up the workflow and should have it done tomorrow.  Where should I put it? Here https://github.com/terraref/documentation/blob/version1/genomic-data-standards.md?

**Comment by craig-willis** [comment]
@phloz 
Great -- yes, feel free to edit that page directly on the version1 branch.

**Comment by nfahlgren** [comment]
@craig-willis that's my only hesitation with the JSON-LD data, I'm not sure where it fits in directly either. When I started putting the table together though, I realized it would be good if we could link to the source definitions for all the fields. The genotypes are all populated in BETYdb I think, maybe this kind of information could be in there?

**Comment by craig-willis** [comment]
@nfahlgren 

I understand your point and have been trying to define a way to reference LD contexts and vocabularies from non-linked data formats like XLS/CSV.

For the spreadsheet, do you know if all of these fields are in BETYdb? (Searching the cultivars table for the accession number, I don't see them)

**Comment by nfahlgren** [comment]
@craig-willis probably not yet. The plant MIxS field set is pretty new, I think they are or recently published it

**Comment by dlebauer** [comment]
Let me know if we need to add genotypes to the cultivars table

**Comment by rachelshekar** [comment]
@craig-willis  and @dlebauer - I'm going to add the list of sorghum lines to the genomics protocol documentation.  

@phloz -  do you have experimental design or protocol documentation?

**Comment by phloz** [comment]
@craig-willis I left the documentation that was in https://github.com/terraref/documentation/blob/version1/genomic-data-standards.md and added to the end.  Please suggest or make any changes as you see fit.

@rachelshekar are you asking for more detail about what's happening within the pipeline?

**Comment by rachelshekar** [comment]
@phloz  I am looking for the experimental design.  How were the plants grown before tissue samples were taken; what was was the replication, what was the DNA extraction protocol...

**Comment by craig-willis** [comment]
@rachelshekar 
Reviewing this open ticket.  The genomic data standards page (https://github.com/terraref/documentation/blob/master/genomic-data-standards.md) seems adequate to me, except maybe removing the two related links at the top.  If I remove those two links, can this ticket be closed?

**Comment by rachelshekar** [comment]
@craig-willis I agree.

**Comment by craig-willis** [comment]
Done. Closing this issue.
