### ISSUE TITLE
Sensor Calibration

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#76]
https://github.com/terraref/documentation/blob/version1/sensor-calibration.md

**Comment by rachelshekar** [comment]
@craig-willis - is this just for the MAC gantry sensors? Do you have any info from Danforth, the MAC UAV, or the phenotractor?

**Comment by nfahlgren** [comment]
We don't do any sensor calibration at the Danforth site, other than what LemnaTec might have done when they installed the system. I can provide the camera specifications though if that's helpful.

**Comment by craig-willis** [comment]
@rachelshekar 
There is a section for UAV calibration, pulled from : https://github.com/terraref/computing-pipeline/issues/185.   I'm not aware of anything for the phenotractor with respect to calibration.

**Comment by craig-willis** [comment]
@rachelshekar @dlebauer 
Can these general documentation issues be closed and new ones opened as needed?
