### ISSUE TITLE
Converting lemnatec scanner metadata to absolute geographic positions

### ISSUE THREAD

**Issue by solmazhajmohammadi** [terraref/documentation#9]
@czender, At the moment there is no accurate GPS at the gantry box. It is planned to add geographical coordinates to metadata, based on the fixed point on the ground and a RTK GPS location.
Here are locations from each corner of the field that @rjstrand sent from his phone:

SE Corner 33° 04.470' N / -111° 58.485' W
SW Corner. 33° 04.474' N / -111° 58.505' W
NW Corner. 33° 04.592' N / -111° 58.505' W
NE Corner. 33° 04.591' N / -111° 58.487' W
  
I have used linear scaling formula to transfer the coordinates, it should be enough for the current GPS location. 

To determine the location of each pixel within the image, Extrinsic and Intrinsic calibration matrices are needed.
3 coordinate systems exist: 
- Field coordinate frame (Xf , Yf , Zf)
- Camera coordinate (Xc , Yc , Zc)
- Image coordinate (Xp , Yp)

1 ) Extrinsic calibration matrix: 
The extrinsic calibration parameters specify the transformation from the field to the camera coordinates, and it is represented as,
[Xc  Yc  Zc]'= Ro  [Xf  Yf  Zf]'+ to
Since there is no rotation (Ro), MEX is only translating vector to. to is transition vector from the control point (0,0,0) to camera position [Xc Yc Zc]. Considering that gantry is moving with constant speed in x direction, and metadata information shows the starting time and start position of a scan.  
to = [+xg+Vx*(t)   +yg   +zg]'  

Where (xg ,yg ,zg ) is the camera position in gantry box. For Hyperspectral camera (xg, yg ,zg ) is (1.9 , 0.855 , 0.635). Vx is velocity in x direction. t represents time difference. ()' is transpose operation.

2 ) Intrinsic calibration matrix: 
Notes:

- The geometric distortions that exist between the 272 bands are considered to be small. 
- No rectification is done. 
- No distortion and lens model is considered.
- Mirror angle change is not considered. 

The intrinsic calibration parameters specify the transformation from the camera coordinate to the pixel coordinates.
Coordinate transformation between camera plane and image plane:
[Xp Yp f]'= **A** [ **I  0** ] [Xc  Yc  Zc]'
Simple orientation matrix is:
 ![stereocalibrate1](https://cloud.githubusercontent.com/assets/17046539/13890132/e71ffdf0-ed17-11e5-9dad-ccf39e0459bd.png)
αx = αy =α and it's focal length divided by pixel pitch. u0 and v0 denote the principal point (ideally center of image) 
For SWIR camera focal length is 24 mm, and pixel pitch is equal to 25 um. I dont know how much is γ. I have contacted the Headwall group and hopefully soon, they will provide me with more information on calibration of the camera. So, I will update your response soon.

**Comment by dlebauer** [comment]
This issue was moved to terraref/reference-data#32
