### ISSUE TITLE
Clean up geospatial information and sensor metadata ... 

### ISSUE THREAD

**Issue by dlebauer** [terraref/documentation#99]
This page seems to confound geospatial information and sensor metadata:

https://terraref.gitbooks.io/terraref-documentation/content/user/geospatial-information.html

needs to be separated, and aimed at end users

--- 

Use cases for such documentation:

* how can a robot operator specify their metadata?: (moved from https://github.com/terraref/sensor-metadata/issues/3)
  * the terraref/sensor-metadata repository has information about the sensor fixed metadata that overlaps with the above documentation
  * But it isn't clear how someone with a new sensor (and sensor platform, e.g. a robot) can specify their metadata. 
  * Some additional fields: latitude, longitude, time, velocity (x, y, z), pitch, roll ... 
* what is required
   * to insert this metadata into Clowder?
  * to extract these metadata and do a geospatial join with sites (plots) in BETYdb

**Comment by craig-willis** [comment]
It looks like we should add some of this information to the gantry fixed metadata:
* Coordinates of the four corners 
* Offset described by Zongyang in  https://github.com/terraref/reference-data/issues/74

**Comment by rachelshekar** [comment]
Have Geo extractor feed to geostream dataset

**Comment by rachelshekar** [comment]
right now we have met data w/ time series.  can also add to canopy cover/height

**Comment by max-zilla** [comment]
I've started adding geostreams API support to pyclowder2:
https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/pyclowder2/browse/pyclowder/geostreams.py

This means any extractor can pull geolocation form metadata and:
- query plots to find nearest one to that point
- push datapoint w/ any values to the correct plot/stream
- query by radius, polygon, or (less often) plot name

**Comment by max-zilla** [comment]
Document to track this effort here:
https://docs.google.com/spreadsheets/d/117n1gOWpiMoXFGWNeYCeI-J1VzSwIwG2uSJcNIFhcRg/edit?usp=sharing

Getting there.

**Comment by max-zilla** [comment]
@craig-willis and I have been in discussions in pursuit of this, including how the format of these metadata influence the type of faceted searches we can support.

**Comment by rachelshekar** [comment]
@craig-willis - can this issue be closed?

**Comment by max-zilla** [comment]
This is being implemented in TERRAutils. we are defining these 'cleaned up' outputs but I don't think we can close yet.
